---
- hosts: localhost
  gather_facts: false
  tasks:
  - name: adding ssh key to powervc
    os_keypair:
      cloud: idXXXXX
      state: present
      name: ansible_key_idXXXXX
      public_key_file:  /home/idXXXXX/.ssh/id_rsa.pub

  - name: Create a new VM instance
    os_server:
      cloud: idXXXXX
      timeout: 900
      state: present
      name: 
      image: AIX721_7022_300G_DEMO
      flavor: was
      key_name: ansible_key_idXXXXX
      nics:
        - net-name: VLAN344
    register: vm
  
  - name: Showing newly assigned IP address 
    debug:
      msg: the IP address is  "{{ vm.server.public_v4 }}"
  - name: Waits for SSH port 22 to open
    wait_for:
      host: "{{ vm.server.public_v4 }}"
      delay: 5
      port: 22
      sleep: 10
      timeout: 900
