- name: Getting real hostname
  command: hostname
  register: real_hostname
- name: Resolve hostname in /etc/hosts
  lineinfile:
    dest: '/etc/hosts'
    regexp: '^{{ ansible_default_ipv4.address }}.*'
    insertafter: '^127.0.0.1 .*localhost*'
    line: "{{ ansible_default_ipv4.address }} {{ real_hostname }}"
    #line: "{{ ansible_default_ipv4.address }} {{ hostname_line }}"
    state: present
    backup: True

- name: Creating staging directory
  file:
    path: /tmp/im
    state: directory

- name: copying IM source files
  unarchive:
    src: /files/aix/websphere/InstallationManager/1.8.9.4/aix.gtk.ppc_1.8.9004.20190423_2015.zip
    dest: /tmp/im
    creates: userinstc.ini
  tags:
    - copyfiles
- name: installing installation manager
  shell: /tmp/im/installc -log /tmp/im.lof -acceptLicense
  tags: installim
- name: uploading was installation response file
  template:
    src: templates/was90501.sdk8035.xml
    dest: /tmp/was90501.sdk8035.xml
  tags: template
- name: Creating wasrepo directory
  file:
    path: "{{was_repo}}"
    state: directory
- name: copying binaries to wasrepo
  copy:
    src: "{{item}}"
    dest: "{{was_repo}}"
  loop:
    - "{{was_90501_source_dir}}{{was_90501_file}}"
    - "{{sdk_8035_source_dir}}{{sdk_8035_file}}"
  #tags: template
- name: installing was using Installation manager
  shell: /opt/IBM/InstallationManager/eclipse/tools/imcl input /tmp/was90501.sdk8035.xml -acceptlicense
  tags: template
- name: creating was profile
  shell: /usr/IBM/WebSphere/AppServer/bin/manageprofiles.sh -create -templatePath /usr/IBM/WebSphere/AppServer/profileTemplates/default
  tags: template
- name: starting application server
  shell: /usr/IBM/WebSphere/AppServer/profiles/AppSrv01/bin/startServer.sh server1
  tags: template

