- name: modifying root capabilities
  ibm.power_aix.user:
    state: modify
    name: root
    attributes:
      fsize: -1
      cpu: -1
      data: -1
      stack: -1
      core: -1
      rss: -1
      nofiles: -1
      fsize_hard: -1


- name: Changes /tmp to 6G size
  aix_filesystem:
    filesystem: /tmp
    size: 6G
    state: present


- name: Changes /var to 2G size
  aix_filesystem:
    filesystem: /var
    size: 2G
    state: present


- name: Changes /opt to 4G size
  aix_filesystem:
    filesystem: /opt
    size: 4G
    state: present


- name: Changes  /usr to 6G
  aix_filesystem:
    filesystem: /usr
    size: 6G
    state: present


- name : installing zip, unzip, GNUtar using yum
  yum:
    name: unzip, zip, tar-1.32-1
    state: latest

- name: Creating staging directory
  file:
    path: /tmp/im
    state: directory

- name: setting ntp server
  template:
    src: templates/ntp.conf
    dest: "/etc/ntp.conf"
    owner: root
    group: system
    mode: '0664'
  tags : xntpd
- name: checking if xntpd is active
  shell: lssrc -s xntpd
  register: lssrc_xntpd
  tags: xntpd
- name: setiing facts
  set_fact:
    xntpd_status: "{{lssrc_xntpd.stdout_lines[1].split()[2]  }}"
  tags: xntpd
- debug:
    msg: "{{xntpd_status}}"
  tags: xntpd
- name: stopping xntpd
  shell: "stopsrc -s xntpd"
  tags: xntpd
  when: xntpd_status != "inoperative"
- name : what is current date ?
  shell: "date"
  tags : xntpd
- name : Syncing clocks
  shell: "ntpdate {{ ansible_facts.default_ipv4.gateway }}"
  tags: xntpd
  when: iscloud is undefined
- name : setting xntpd to autostarti
  shell: "chrctcp -S -a xntpd"
  tags : xntpd
  when: iscloud is undefined

