- name: Create a new VM instance
  os_server:
    cloud: "{{cloud_name}}"
    timeout: 900
    state: present
    name: "{{item}}"
    image: "{{ pvc_image_name }}"
    flavor: "{{ pvc_flavor }}"
    key_name: "{{ key_name }}"
    nics:
      - net-name: "{{vlan_name}}"
  register: vm

- name: set hostip with  VM's public IP address
  set_fact:
    hostip: "{{vm.server.public_v4}}"
- name: getting fqdn for created vm
  set_fact:
    fqdn:  "{{ lookup('dig',  vm.server.public_v4 , 'qtype=PTR') }}"
- name: Adding ip address to list
  set_fact:
    ip_adresses: "{{ ip_adresses }} + [ '{{ hostip}}' ]"  
- name: Add host just_created to just_added group
  add_host:
    name: "{{fqdn}}"
    group: just_added
    remote_tmp: /tmp/${USER}/ansible
